# Generated by Django 3.0.8 on 2020-08-12 22:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appstorereview',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.App'),
        ),
        migrations.AddField(
            model_name='app',
            name='similar',
            field=models.ManyToManyField(blank=True, related_name='_app_similar_+', to='data.App'),
        ),
        migrations.AlterUniqueTogether(
            name='app',
            unique_together={('appid', 'primaryCountry')},
        ),
    ]
