# Generated by Django 3.0.8 on 2020-07-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_customer_watchlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="app",
            name="primaryCountry",
            field=models.CharField(default="us", max_length=2),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="app", unique_together={("appid", "primaryCountry")},
        ),
    ]
