# Generated by Django 3.0.8 on 2020-08-13 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20200812_2356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='app',
            new_name='apps',
        ),
    ]
