# Generated by Django 3.0.8 on 2020-08-15 00:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200815_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayStoreReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, null=True)),
                ('version', models.CharField(max_length=15)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(null=True)),
                ('country', models.CharField(max_length=2, null=True)),
                ('authorImg', models.URLField()),
                ('reviewedAt', models.DateTimeField()),
                ('replyContent', models.TextField()),
                ('repliedAt', models.DateTimeField()),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.App')),
            ],
            options={
                'ordering': ['-reviewedAt'],
            },
        ),
    ]
