# Generated by Django 3.0.8 on 2020-08-15 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0008_playstorereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='playstorereview',
            name='reviewId',
            field=models.CharField(max_length=220, null=True, verbose_name='Review ID'),
        ),
        migrations.AddField(
            model_name='playstorereview',
            name='thumbsUpCount',
            field=models.IntegerField(default=0),
        ),
    ]
