# Generated by Django 3.0.8 on 2020-08-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0009_auto_20200815_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playstorereview',
            name='authorImg',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='repliedAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='replyContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='reviewId',
            field=models.CharField(blank=True, max_length=220, null=True, verbose_name='Review ID'),
        ),
    ]
