# Generated by Django 3.0.8 on 2020-08-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0010_auto_20200818_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstorereview',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='appstorereview',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appstorereview',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='appstorereview',
            name='version',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='author',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='country',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='version',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
