# Generated by Django 3.0.8 on 2020-08-21 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0011_auto_20200818_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appstorereview',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appstorereview_reviews', to='data.App'),
        ),
        migrations.AlterField(
            model_name='playstorereview',
            name='app',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='playstorereview_reviews', to='data.App'),
        ),
    ]
