# Generated by Django 3.0.8 on 2020-08-25 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0012_auto_20200821_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='appstorereview',
            name='appid',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
