# Generated by Django 3.0.8 on 2020-09-02 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0013_appstorereview_appid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='customer',
        ),
    ]
