# Generated by Django 3.0.8 on 2020-09-02 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0014_remove_watchlist_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='customer',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='data.Customer'),
        ),
    ]
